name: publish package
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "{{ secrets.MAVEN_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "{{ secrets.MAVEN_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingPassword: "{{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "{{ secrets.MAVEN_GPG_SECRET_KEY }}"

